using System;

namespace WeeklyReportSystem.Models
{
    public class Comment
    {
        public int CommentID { get; set; } // This will be auto-generated by EF Core
        public string CommentText { get; set; }
        public DateTime CreatedAt { get; set; }
        public int TicketID { get; set; }
        public int UserID { get; set; }
        public byte[]? CommentImage { get; set; } // Add this line for image storage

        // Navigation properties
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
